### ISSUE TITLE
I would like to work with you.

### ISSUE THREAD

**Issue by kentaurse** [venture-technology/vtx-invites#2]
I saw your organization's projects on GitHub.
As an experienced blockchain and work full-stack developer, I am looking for projects where I can leverage my expertise in decentralized applications, smart contracts, and blockchain integration to drive innovative solutions and contribute to your success.
I understand that the project is still in progress.
If you need a developer, please contact me.

**Comment by gurodrigues-dev** [comment]
Hello @kentaurse, how are you?

At the moment, yet don't searching new devs front-end, because our app startings at microservices, but will need in some days. How can I contact you? Please ask me in `gustavorodrigueslima2004@gmail.com`

**Comment by kentaurse** [comment]
thx

**Comment by kentaurse** [comment]
I have published my contact information on my GitHub.
You can contact me here.
